### ISSUE TITLE
The empty of functions

### ISSUE THREAD

**Issue by nodtem66** [ianstormtaylor/is-empty#9]
Current usage of empty for function is:
```javascript
empty(function(){}); // true
empty(function(a,b){}); // false
```
then `empty(function() { return 1; });` should be ***false*** logically, but it failed (see: [Runkit](https://runkit.com/nodtem66/58b58abda7a1a60014361cb2)).

According to the [jfriend00's answer](http://stackoverflow.com/questions/7960335/javascript-is-given-function-empty), coding to check the empty of function's body is **no totally reliable**.
Shouldn't the empty of all functions be ***false***, like the empty of all boolean?

**Comment by ianstormtaylor** [comment]
Hey @nodtem66, sorry for the confusion here. The "emptiness" of functions that I originally added was for checking `function.length` which checks if the function takes no arguments, not if it has an empty function body.

I would agree that it's probably not the most useful of the cases though. 

I probably wouldn't want to major bump right now to remove it, but I could be down to consider removing that piece in the future.

Thanks!

**Comment by Eli-Black-Work** [comment]
This seems confusing to me, too. I'd expect `empty()` to return `false` for all functions.
